version: '3.8'

services:
  # Service pour l'application web
  web:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: examen-web-app
    ports:
      - "3001:3000"
    environment:
      - NODE_ENV=production
      - PORT=3000
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    depends_on:
      - redis
    networks:
      - app-network
    restart: unless-stopped

  # Service pour Redis (base de données en mémoire)
  redis:
    image: redis:7-alpine
    container_name: examen-redis
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    networks:
      - app-network
    restart: unless-stopped
    command: redis-server --appendonly yes

  # Service pour Nginx 
  nginx:
    image: nginx:alpine
    container_name: examen-nginx
    ports:
      - "70:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - web
    networks:
      - app-network
    restart: unless-stopped

# Réseau pour permettre la communication entre les conteneurs
networks:
  app-network:
    driver: bridge

# Volumes pour la persistance des données
volumes:
  redis-data:

